### ISSUE TITLE
关于CSS文字溢出问题

### ISSUE THREAD

**Issue by NvanYu** [NvanYu/Blog#5]
## 单行文本溢出显示省略号
```css
// （需要对容器设置单行高度）
overflow:hidden;
text-overflow:ellipsis;
white-space:nowrap;
```

## 多行文本溢出显示省略号
1. 非兼容写法
```css
.box {
    width: 400px; 
    display: -webkit-box;     // 必须结合的属性，将对象作为弹性伸缩盒子模型展示
    -webkit-line-clamp: 3;   // 用来限制在一个块元素显示的文本行数，为了实现效果，他要与一下webkit属性结合使用：
    -webkit-box-orient: vertical;   // 必须结合的属性，设置或检索伸缩盒对象的子元素的排列方式
    overflow: hidden;
}
```

2. 兼容写法
比较靠谱简单的做法就是设置相对定位的容器高度，用包含省略号（...）的元素模拟实现
```css
p{
  position:relative;
  line-height:1.4em;
  /*设置容器高度为3倍行高就是显示3行*/
  height:4.2em;
  overflow:hidden;
}
p::after{
  content:'...';
  font-weight:bold;
  position:absolute;
  bottom:0;
  right:0;
  padding:0 20px 1px 45px;
  background:#fff;
}
```
